---
apiVersion: v1
kind: Secret
metadata:
  name: bgg-secret
  namespace: bggns
data:
  BGG_DB_PASSWORD: cm9vdHJvb3Q=

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bgg-cm
  namespace: bggns
data:
  BGG_DB_HOST: "bggdb-svc.bggns.svc.cluster.local"
  BGG_PORT: "5000"
  BGG_DB_USER: "root"
